-- =====================================================
-- Chạy đoạn SQL này trong Supabase SQL Editor
-- (Dashboard > SQL Editor > New Query > Paste & Run)
-- =====================================================

CREATE OR REPLACE FUNCTION get_hist5m_positive_zones(filter_tf text DEFAULT NULL)
RETURNS TABLE (
  zone_id int,
  start_time timestamptz,
  end_time timestamptz,
  candles int,
  entry_price numeric,
  max_high numeric,
  min_low numeric,
  max_gain numeric,
  max_drop numeric
) AS $$
DECLARE
  rec record;
  prev_hist numeric := -1;
  in_zone boolean := false;
  z_id int := 0;
  z_start timestamptz;
  z_entry numeric;
  z_max_high numeric;
  z_min_low numeric;
  z_candles int;
  z_end timestamptz;
BEGIN
  FOR rec IN
    SELECT r.open_time, r.open, r.high, r.low, r.close,
           r.hist_5m, r.hist_1h, r.hist_4h, r.hist_1d
    FROM "BTCJPY" r
    WHERE r.hist_5m IS NOT NULL
    ORDER BY r.open_time ASC
  LOOP
    -- Detect transition: hist_5m crosses from <=0 to >0
    IF NOT in_zone AND prev_hist <= 0 AND rec.hist_5m > 0 THEN
      -- Apply higher-TF filter at zone entry
      IF filter_tf = '1h' AND (rec.hist_1h IS NULL OR rec.hist_1h <= 0) THEN
        prev_hist := rec.hist_5m;
        CONTINUE;
      END IF;
      IF filter_tf = '4h' AND (rec.hist_4h IS NULL OR rec.hist_4h <= 0) THEN
        prev_hist := rec.hist_5m;
        CONTINUE;
      END IF;
      IF filter_tf = '1d' AND (rec.hist_1d IS NULL OR rec.hist_1d <= 0) THEN
        prev_hist := rec.hist_5m;
        CONTINUE;
      END IF;

      in_zone := true;
      z_id := z_id + 1;
      z_start := rec.open_time;
      z_entry := rec.open;
      z_max_high := rec.high;
      z_min_low := rec.low;
      z_candles := 1;
      z_end := rec.open_time;

    ELSIF in_zone AND rec.hist_5m > 0 THEN
      z_candles := z_candles + 1;
      IF rec.high > z_max_high THEN z_max_high := rec.high; END IF;
      IF rec.low < z_min_low THEN z_min_low := rec.low; END IF;
      z_end := rec.open_time;

    ELSIF in_zone AND rec.hist_5m <= 0 THEN
      zone_id := z_id;
      start_time := z_start;
      end_time := z_end;
      candles := z_candles;
      entry_price := z_entry;
      max_high := z_max_high;
      min_low := z_min_low;
      max_gain := z_max_high - z_entry;
      max_drop := z_entry - z_min_low;
      RETURN NEXT;
      in_zone := false;
    END IF;

    prev_hist := rec.hist_5m;
  END LOOP;

  -- Return last zone if still open
  IF in_zone THEN
    zone_id := z_id;
    start_time := z_start;
    end_time := z_end;
    candles := z_candles;
    entry_price := z_entry;
    max_high := z_max_high;
    min_low := z_min_low;
    max_gain := z_max_high - z_entry;
    max_drop := z_entry - z_min_low;
    RETURN NEXT;
  END IF;
END;
$$ LANGUAGE plpgsql;


-- =====================================================
-- api_account: thêm tài khoản Binance Testnet
-- Chạy trong Supabase SQL Editor (chỉ cần chạy 1 lần)
-- =====================================================

INSERT INTO public.api_account (config, "Name", "Platform")
SELECT
  '{
    "apiKey": "XnBzL1Ynkz70n2nE64TJLJGyRQq01f3v5vRftGR23C7gox8sny1gb588fswtTNUO",
    "secretKey": "S50V703nXe9zSxldBwXzHA0gBUv0kpe9xEDK0bx5HP6i99V4bdhAi2B1opyK2Fvu",
    "testnet": true
  }'::jsonb,
  'Binance Testnet',
  'Binance'
WHERE NOT EXISTS (SELECT 1 FROM public.api_account LIMIT 1);


-- =====================================================
-- Bảng lưu lịch sử giao dịch (đồng bộ từ Binance myTrades)
-- Cấu trúc tương ứng với API GET /api/v3/myTrades
-- =====================================================

CREATE TABLE IF NOT EXISTS public.trade_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  account_id bigint NOT NULL,
  symbol text NOT NULL,
  binance_trade_id bigint NOT NULL,
  order_id bigint NOT NULL,
  side text NOT NULL,
  price numeric NOT NULL,
  qty numeric NOT NULL,
  quote_qty numeric NOT NULL,
  commission numeric NOT NULL DEFAULT 0,
  commission_asset text,
  trade_time timestamptz NOT NULL,
  is_buyer boolean NOT NULL DEFAULT true,
  is_maker boolean NOT NULL DEFAULT false,
  raw jsonb,
  CONSTRAINT trade_history_account_fk
    FOREIGN KEY (account_id) REFERENCES public.api_account (id) ON DELETE CASCADE,
  CONSTRAINT trade_history_account_binance_id_uniq
    UNIQUE (account_id, binance_trade_id)
);

CREATE INDEX IF NOT EXISTS idx_trade_history_account_id ON public.trade_history (account_id);
CREATE INDEX IF NOT EXISTS idx_trade_history_trade_time ON public.trade_history (trade_time DESC);
CREATE INDEX IF NOT EXISTS idx_trade_history_symbol ON public.trade_history (symbol);

COMMENT ON TABLE public.trade_history IS 'Lịch sử giao dịch đồng bộ từ Binance myTrades (BTC, USDT, FDUSD, JPY liên quan)';
COMMENT ON COLUMN public.trade_history.binance_trade_id IS 'ID giao dịch từ Binance (tránh trùng khi sync)';
COMMENT ON COLUMN public.trade_history.raw IS 'Payload đầy đủ từ Binance API (tùy chọn)';


-- =====================================================
-- Bảng lưu lịch sử tin nhắn Telegram (conversation memory)
-- =====================================================

CREATE TABLE IF NOT EXISTS public.telegram_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  chat_id bigint NOT NULL,
  role text NOT NULL CHECK (role IN ('user', 'assistant', 'system', 'tool')),
  content text,
  tool_calls jsonb,
  tool_call_id text,
  name text
);

CREATE INDEX IF NOT EXISTS idx_tg_msg_chat_id_created ON public.telegram_messages (chat_id, created_at DESC);

COMMENT ON TABLE public.telegram_messages IS 'Lưu lịch sử hội thoại Telegram để AI ghi nhớ ngữ cảnh';
COMMENT ON COLUMN public.telegram_messages.chat_id IS 'Telegram chat_id để phân biệt cuộc trò chuyện';
COMMENT ON COLUMN public.telegram_messages.role IS 'user | assistant | system | tool';
COMMENT ON COLUMN public.telegram_messages.tool_calls IS 'Lưu tool_calls khi AI gọi function';
COMMENT ON COLUMN public.telegram_messages.tool_call_id IS 'ID của tool call (cho role=tool)';
